resources:
- namespace_creation.yaml

helmCharts:
- name: falcon-sensor
  repo: https://crowdstrike.github.io/falcon-helm
  version: v1.20.3
  releaseName: falcon-helm
  namespace: falcon-system
  skipHooks: true
  valuesInline:
    falcon:
      cid: "00001111222233334444555566667777-12"
      tags: "sidecar"
    container:
      enabled: true
    node:
      enabled: false

