
resources:
- ../../../base/kpa-with-proxy


configMapGenerator:
- name: kpagent-cs-k8s-protection-agent
  namespace: falcon-kubernetes-protection
  behavior: merge
  literals:
  - AGENT_CLUSTER_NAME="CHANGE_ME_TO_YOUR_CLUSTER_NAME"
  - HTTP_PROXY="http://MY_PROXY:MY_PROXY_PORT"
  - HTTPS_PROXY="http://MY_PROXY:MY_PROXY_PORT"